<?php

// Prevent direct file access.
defined( 'ABSPATH' ) || die;

// Instantiate the class.
new Mai_Locations_Settings;

/**
 * Adds settings page.
 *
 * Original code generated by the WordPress Option Page generator:
 * @link http://jeremyhixon.com/wp-tools/option-page/
 */
class Mai_Locations_Settings {
	private $options;

	/**
	 * Construct the class.
	 *
	 * @since TBD
	 *
	 * @return void
	 */
	function __construct() {
		add_action( 'admin_menu',                                          [ $this, 'add_menu_item' ], 12 );
		add_action( 'admin_init',                                          [ $this, 'init' ] );
		add_filter( 'acf/fields/google_map/api',                           [ $this, 'acf_google_map_api' ], 99 );
		add_filter( 'plugin_action_links_mai-locations/mai-locations.php', [ $this, 'add_settings_link' ], 10, 4 );
	}

	/**
	 * Adds menu item for settings page.
	 *
	 * @since TBD
	 *
	 * @return void
	 */
	function add_menu_item() {
		add_submenu_page(
			'edit.php?post_type=mai_location',
			__( 'Mai Locations', 'mai-locations' ), // page_title
			__( 'Settings', 'mai-locations' ), // menu_title
			'manage_options', // capability
			'mai-locations', // menu_slug
			[ $this, 'add_content' ], // callback
		);
	}

	/**
	 * Adds setting page content.
	 *
	 * @since TBD
	 *
	 * @return void
	 */
	function add_content() {
		$defaults                        = mailocations_get_options_defaults();
		$this->options                   = mailocations_get_options();
		$this->options['label_plural']   = $this->options['label_plural'] ?: $defaults['label_plural'];
		$this->options['label_singular'] = $this->options['label_singular'] ?: $defaults['label_singular'];
		$this->options['base']           = $this->options['base'] ?: $defaults['base'];
		$this->options['category_base']  = $this->options['category_base'] ?: $defaults['category_base'];

		echo '<div class="wrap">';
			printf( '<h2>%s</h2>', __( 'Mai Locations', 'mai-locations' ) );

			echo '<form method="post" action="options.php">';
				settings_fields( 'mai_locations_group' );
				do_settings_sections( 'mai-locations-section' );
				submit_button();
			echo '</form>';
		echo '</div>';
	}

	/**
	 * Initialize the settings.
	 *
	 * @since TBD
	 *
	 * @return void
	 */
	function init() {
		register_setting(
			'mai_locations_group', // option_group
			'mai_locations', // option_name
			[ $this, 'sanitize_callback' ] // sanitize_callback
		);

		add_settings_section(
			'mai_locations_settings', // id
			'', // title
			[ $this, 'settings_callback' ], // callback
			'mai-locations-section' // page
		);

		add_settings_field(
			'label_plural', // id
			__( 'Plural Label', 'mai-locations' ), // title
			[ $this, 'label_plural_callback' ], // callback
			'mai-locations-section', // page
			'mai_locations_settings' // section
		);

		add_settings_field(
			'label_singular', // id
			__( 'Singular Label', 'mai-locations' ), // title
			[ $this, 'label_singular_callback' ], // callback
			'mai-locations-section', // page
			'mai_locations_settings' // section
		);

		add_settings_field(
			'base', // id
			__( 'Permalinks', 'mai-locations' ), // title
			[ $this, 'base_callback' ], // callback
			'mai-locations-section', // page
			'mai_locations_settings' // section
		);

		add_settings_field(
			'category_base', // id
			__( 'Category Permalinks', 'mai-locations' ), // title
			[ $this, 'category_base_callback' ], // callback
			'mai-locations-section', // page
			'mai_locations_settings' // section
		);

		add_settings_field(
			'distance', // id
			__( 'Default Distance', 'mai-locations' ), // title
			[ $this, 'distance_callback' ], // callback
			'mai-locations-section', // page
			'mai_locations_settings' // section
		);

		add_settings_field(
			'units', // id
			__( 'Default Units', 'mai-locations' ), // title
			[ $this, 'units_callback' ], // callback
			'mai-locations-section', // page
			'mai_locations_settings' // section
		);

		add_settings_field(
			'google_api_key', // id
			__( 'Google API Key', 'mai-locations' ), // title
			[ $this, 'google_api_key_callback' ], // callback
			'mai-locations-section', // page
			'mai_locations_settings' // section
		);

		add_settings_field(
			'google_api_signature', // id
			__( 'Google API Signature', 'mai-locations' ), // title
			[ $this, 'google_api_signature_callback' ], // callback
			'mai-locations-section', // page
			'mai_locations_settings' // section
		);

	}

	/**
	 * Sanitized saved values.
	 *
	 * @param array $input
	 *
	 * @return array
	 */
	function sanitize_callback( $input ) {
		return mailocations_sanitize_options( $input );
	}

	/**
	 * Displays HTML before settings.
	 *
	 * @return string
	 */
	function settings_callback() {}

	/**
	 * Setting callback.
	 *
	 * @since TBD
	 *
	 * @return void
	 */
	function label_plural_callback() {
		printf( '<input class="regular-text" type="text" name="mai_locations[label_plural]" id="label_plural" value="%s">', $this->options['label_plural'] );
	}

	/**
	 * Setting callback.
	 *
	 * @since TBD
	 *
	 * @return void
	 */
	function label_singular_callback() {
		printf( '<input class="regular-text" type="text" name="mai_locations[label_singular]" id="label_singular" value="%s">', $this->options['label_singular'] );
	}

	/**
	 * Setting callback.
	 *
	 * @since TBD
	 *
	 * @return void
	 */
	function base_callback() {
		$instructions = sprintf( '<a href="%s">%s</a>', get_admin_url( null, 'options-permalink.php' ), __( 'Permalinks', 'mai-locations' ) );
		$instructions = sprintf( __( 'Visit Dashboard > Settings > %s and hit "Save" if updating this setting.', 'mai-locations' ), $instructions );

		printf( '<input class="regular-text" type="text" name="mai_locations[base]" id="base" value="%s">', $this->options['base'] );
		printf( '<p>%s</p>', $instructions );
	}

	/**
	 * Setting callback.
	 *
	 * @since TBD
	 *
	 * @return void
	 */
	function category_base_callback() {
		$instructions = sprintf( '<a href="%s">%s</a>', get_admin_url( null, 'options-permalink.php' ), __( 'Permalinks', 'mai-locations' ) );
		$instructions = sprintf( __( 'Visit Dashboard > Settings > %s and hit "Save" if updating this setting.', 'mai-locations' ), $instructions );

		printf( '<input class="regular-text" type="text" name="mai_locations[category_base]" id="category_base" value="%s">', $this->options['category_base'] );
		printf( '<p>%s</p>', $instructions );
	}

	/**
	 * Setting callback.
	 *
	 * @since TBD
	 *
	 * @return void
	 */
	function distance_callback() {
		printf( '<input type="number" name="mai_locations[distance]" id="distance" value="%s">', $this->options['distance'] );
		printf( '<p>%s</p>', __( 'The default distance used for proximity search.', 'mai-locations' ) );
	}

	/**
	 * Setting callback.
	 *
	 * @since TBD
	 *
	 * @return void
	 */
	function units_callback() {
		$selected = (string) $this->options['units'];
		$options  = [
			'mi' => __( 'Miles', 'mai-locations' ),
			'km' => __( 'Kilometers', 'mai-locations' ),
		];

		echo '<select name="mai_locations[units]">';
			foreach ( $options as $id => $label ) {
				printf( '<option value="%s"%s>%s</option>', $id, selected( $selected, $id ), $label );
			}
		echo '</select>';

		printf( '<p>%s</p>', __( 'The default distance unit used for proximity search.', 'mai-locations' ) );
	}

	/**
	 * Setting callback.
	 *
	 * @since TBD
	 *
	 * @return void
	 */
	function google_api_key_callback() {
		printf( '<input class="regular-text" type="password" name="mai_locations[google_api_key]" id="google_api_key" value="%s">', $this->options['google_api_key'] );
		echo '<p>';
			printf( '%s <a href="https://developers.google.com/maps/documentation/javascript/get-api-key" target="_blank">%s</a>',
				__( 'The Google API key for maps in ACF and the Location Map block.', 'mai-locations' ),
				__( 'Get a key.', 'mai-locations' )
			);
		echo '</p>';
	}

	/**
	 * Setting callback.
	 *
	 * @since TBD
	 *
	 * @return void
	 */
	function google_api_signature_callback() {
		printf( '<input class="regular-text" type="password" name="mai_locations[google_api_signature]" id="google_api_signature" value="%s">', $this->options['google_api_signature'] );
	}

	/**
	 * ACF Google Maps API.
	 *
	 * @since TBD
	 *
	 * @param string $api The API data.
	 *
	 * @return array
	 */
	function acf_google_map_api( $api ) {
		// Bail if not in the Dashboard.
		if ( ! is_admin() ) {
			return $api;
		}

		// Get the current screen.
		$screen = get_current_screen();

		// Bail if not on the Locations post type.
		if ( ! $screen || 'mai_location' !== $screen->post_type ) {
			return $api;
		}

		// Maybe add key.
		if ( isset( $api['key'] ) || empty( $api['key'] ) ) {
			$key = mailocations_get_option( 'google_api_key' );

			if ( $key ) {
				$api['key'] = $key;
			}
		}

		// Maybe add signature.
		if ( isset( $api['signature'] ) || empty( $api['signature'] ) ) {
			$signature = mailocations_get_option( 'google_api_signature' );

			if ( $signature ) {
				$api['signature'] = $signature;
			}
		}

		return $api;
	}

	/**
	 * Return the plugin action links.  This will only be called if the plugin is active.
	 *
	 * @since TBD
	 *
	 * @param array  $actions     Associative array of action names to anchor tags
	 * @param string $plugin_file Plugin file name, ie my-plugin/my-plugin.php
	 * @param array  $plugin_data Associative array of plugin data from the plugin file headers
	 * @param string $context     Plugin status context, ie 'all', 'active', 'inactive', 'recently_active'
	 *
	 * @return array associative array of plugin action links
	 */
	function add_settings_link( $actions, $plugin_file, $plugin_data, $context ) {
		$url                 = esc_url( admin_url( 'edit.php?post_type=mai_location' ) );
		$link                = sprintf( '<a href="%s">%s</a>', $url, __( 'Settings', 'mai-locations' ) );
		$actions['settings'] = $link;

		return $actions;
	}
}
