<?php

declare(strict_types=1);

namespace Mai\Locations\Admin;

// Prevent direct file access.
defined( 'ABSPATH' ) || die;

/**
 * The settings page under Locations.
 *
 * Was Mai_Locations_Settings in classes/class-settings.php, which instantiated itself at the
 * bottom of the file. The bootstrap does that now. The old name still works, via
 * inc/aliases.php.
 *
 * Original code generated by the WordPress Option Page generator:
 *
 * @link http://jeremyhixon.com/wp-tools/option-page/
 *
 * @since TBD
 */
class Settings {

	/**
	 * The saved options, loaded when the page renders.
	 *
	 * @var array<string, mixed>
	 */
	private $options;

	/**
	 * Construct the class.
	 *
	 * @since TBD
	 */
	public function __construct() {
		add_action( 'admin_menu',                                          [ $this, 'add_menu_item' ], 12 );
		add_action( 'admin_init',                                          [ $this, 'init' ] );
		add_filter( 'acf/fields/google_map/api',                           [ $this, 'acf_google_map_api' ], 99 );
		// Built from the plugin's own file, not the folder name, which used to be hardcoded and
		// so failed on any site that renamed the folder. Fixed September 16, 2026.
		add_filter( 'plugin_action_links_' . plugin_basename( MAI_LOCATIONS_PLUGIN_FILE ), [ $this, 'add_settings_link' ], 10, 4 );
	}

	/**
	 * Adds the menu item for the settings page.
	 *
	 * @since TBD
	 *
	 * @return void
	 */
	public function add_menu_item(): void {
		add_submenu_page(
			'edit.php?post_type=mai_location',
			__( 'Mai Locations', 'mai-locations' ), // page_title
			__( 'Settings', 'mai-locations' ), // menu_title
			'manage_options', // capability
			'mai-locations', // menu_slug
			[ $this, 'add_content' ], // callback
		);
	}

	/**
	 * Displays the settings page content.
	 *
	 * @since TBD
	 *
	 * @return void
	 */
	public function add_content(): void {
		$defaults                        = mailocations_get_options_defaults();
		$this->options                   = mailocations_get_options();
		$this->options['label_plural']   = $this->options['label_plural'] ?: $defaults['label_plural'];
		$this->options['label_singular'] = $this->options['label_singular'] ?: $defaults['label_singular'];
		$this->options['base']           = $this->options['base'] ?: $defaults['base'];
		$this->options['category_base']  = $this->options['category_base'] ?: $defaults['category_base'];

		echo '<div class="wrap">';
			printf( '<h2>%s</h2>', __( 'Mai Locations', 'mai-locations' ) );

			echo '<form method="post" action="options.php">';
				settings_fields( 'mai_locations_group' );
				do_settings_sections( 'mai-locations-section' );
				submit_button();
			echo '</form>';
		echo '</div>';
	}

	/**
	 * Registers the setting, its section and its fields.
	 *
	 * @since TBD
	 *
	 * @return void
	 */
	public function init(): void {
		register_setting(
			'mai_locations_group', // option_group
			'mai_locations', // option_name
			[ $this, 'sanitize_callback' ] // sanitize_callback
		);

		add_settings_section(
			'mai_locations_settings', // id
			'', // title
			[ $this, 'settings_callback' ], // callback
			'mai-locations-section' // page
		);

		$fields = [
			'label_plural'         => __( 'Plural Label', 'mai-locations' ),
			'label_singular'       => __( 'Singular Label', 'mai-locations' ),
			'base'                 => __( 'Permalinks', 'mai-locations' ),
			'category_base'        => __( 'Category Permalinks', 'mai-locations' ),
			'owners_can_publish'   => __( 'Publishing', 'mai-locations' ),
			'distance'             => __( 'Default Distance', 'mai-locations' ),
			'units'                => __( 'Default Units', 'mai-locations' ),
			'google_api_key'       => __( 'Google API Key', 'mai-locations' ),
			'google_api_signature' => __( 'Google API Signature', 'mai-locations' ),
			'google_map_id'        => __( 'Google Map ID', 'mai-locations' ),
		];

		foreach ( $fields as $id => $title ) {
			add_settings_field(
				$id, // id
				$title, // title
				[ $this, "{$id}_callback" ], // callback
				'mai-locations-section', // page
				'mai_locations_settings' // section
			);
		}
	}

	/**
	 * Sanitizes saved values.
	 *
	 * @since TBD
	 *
	 * @param array<string, mixed> $input The submitted values.
	 *
	 * @return array<string, mixed>
	 */
	public function sanitize_callback( $input ) {
		return mailocations_sanitize_options( $input );
	}

	/**
	 * Displays HTML before the settings. Empty today.
	 *
	 * @since TBD
	 *
	 * @return void
	 */
	public function settings_callback(): void {}

	/**
	 * Setting callback.
	 *
	 * @since TBD
	 *
	 * @return void
	 */
	public function label_plural_callback(): void {
		printf( '<input class="regular-text" type="text" name="mai_locations[label_plural]" id="label_plural" value="%s">', esc_attr( $this->options['label_plural'] ) );
	}

	/**
	 * Setting callback.
	 *
	 * @since TBD
	 *
	 * @return void
	 */
	public function label_singular_callback(): void {
		printf( '<input class="regular-text" type="text" name="mai_locations[label_singular]" id="label_singular" value="%s">', esc_attr( $this->options['label_singular'] ) );
	}

	/**
	 * Setting callback.
	 *
	 * @since TBD
	 *
	 * @return void
	 */
	public function base_callback(): void {
		printf( '<input class="regular-text" type="text" name="mai_locations[base]" id="base" value="%s">', esc_attr( $this->options['base'] ) );
		printf( '<p>%s</p>', $this->permalink_instructions() );
	}

	/**
	 * Setting callback.
	 *
	 * @since TBD
	 *
	 * @return void
	 */
	public function category_base_callback(): void {
		printf( '<input class="regular-text" type="text" name="mai_locations[category_base]" id="category_base" value="%s">', esc_attr( $this->options['category_base'] ) );
		printf( '<p>%s</p>', $this->permalink_instructions() );
	}

	/**
	 * Setting callback.
	 *
	 * @since TBD
	 *
	 * @return void
	 */
	public function distance_callback(): void {
		printf( '<input type="number" name="mai_locations[distance]" id="distance" value="%s">', esc_attr( $this->options['distance'] ) );
		printf( '<p>%s</p>', __( 'The default distance used for proximity search.', 'mai-locations' ) );
	}

	/**
	 * The Publishing checkbox, and the help text that explains the three ways sites run this.
	 *
	 * This is the only place a site manager meets the decision, so the explanation lives here
	 * rather than in a readme nobody opens.
	 *
	 * @since 2.0.0
	 *
	 * @return void
	 */
	public function owners_can_publish_callback(): void {
		printf(
			'<label><input type="checkbox" id="owners_can_publish" name="mai_locations[owners_can_publish]" value="1"%s> %s</label>',
			checked( (bool) $this->options['owners_can_publish'], true, false ),
			esc_html__( 'Let location owners publish their own locations', 'mai-locations' )
		);

		printf(
			'<p>%s</p>',
			esc_html__( 'A location owner sees a Publish switch on the front-end edit form, but only while their location is a draft. Anyone whose role can already publish, such as an editor, can always publish, whatever this is set to.', 'mai-locations' )
		);

		printf( '<p><strong>%s</strong></p>', esc_html__( 'Three ways to run this:', 'mai-locations' ) );

		echo '<ul style="list-style:disc;margin-left:20px;">';
			printf(
				'<li>%s<br>%s</li>',
				esc_html__( 'A manager approves everything.', 'mai-locations' ),
				esc_html__( 'Leave this unticked, and set the Submission Form block\'s Location Status to Pending. Owners edit their listing. You publish it from Locations in the Dashboard.', 'mai-locations' )
			);
			printf(
				'<li>%s<br>%s</li>',
				esc_html__( 'Owners run their own listing.', 'mai-locations' ),
				esc_html__( 'Tick this, and set the Submission Form block\'s Location Status to Draft. Owners finish their listing and publish it when they are ready.', 'mai-locations' )
			);
			printf(
				'<li>%s<br>%s</li>',
				esc_html__( 'You approve, then the owner picks the moment.', 'mai-locations' ),
				esc_html__( 'Tick this, and set the Submission Form block\'s Location Status to Pending. Review what arrives, and change an approved one to Draft. Its owner then publishes when they are ready.', 'mai-locations' )
			);
		echo '</ul>';
	}

	/**
	 * Setting callback.
	 *
	 * @since TBD
	 *
	 * @return void
	 */
	public function units_callback(): void {
		$selected = (string) $this->options['units'];
		$options  = [
			'mi' => __( 'Miles', 'mai-locations' ),
			'km' => __( 'Kilometers', 'mai-locations' ),
		];

		echo '<select name="mai_locations[units]">';
			foreach ( $options as $id => $label ) {
				// The third argument stops selected() echoing as well as returning, which used to
				// print a stray selected='selected' before the first option. Fixed September 16, 2026.
				printf( '<option value="%s"%s>%s</option>', $id, selected( $selected, $id, false ), $label );
			}
		echo '</select>';

		printf( '<p>%s</p>', __( 'The default distance unit used for proximity search.', 'mai-locations' ) );
	}

	/**
	 * Setting callback.
	 *
	 * @since TBD
	 *
	 * @return void
	 */
	public function google_api_key_callback(): void {
		printf( '<input class="regular-text" type="password" name="mai_locations[google_api_key]" id="google_api_key" value="%s">', esc_attr( $this->options['google_api_key'] ) );
		echo '<p>';
			printf( '%s <a href="https://developers.google.com/maps/documentation/javascript/get-api-key" target="_blank">%s</a>',
				__( 'Needed for maps and address search.', 'mai-locations' ),
				__( 'Get a key.', 'mai-locations' )
			);
		echo '</p>';
	}

	/**
	 * Setting callback.
	 *
	 * @since TBD
	 *
	 * @return void
	 */
	public function google_api_signature_callback(): void {
		printf( '<input class="regular-text" type="password" name="mai_locations[google_api_signature]" id="google_api_signature" value="%s">', esc_attr( $this->options['google_api_signature'] ) );
	}

	/**
	 * Setting callback.
	 *
	 * @since TBD
	 *
	 * @return void
	 */
	public function google_map_id_callback(): void {
		printf( '<input class="regular-text" type="text" name="mai_locations[google_map_id]" id="google_map_id" value="%s">', esc_attr( $this->options['google_map_id'] ) );
		echo '<p>';
			printf( '%s <a href="https://console.cloud.google.com/google/maps-apis/studio/maps" target="_blank">%s</a>',
				__( 'From Google Cloud Console. Needed for the newer map markers.', 'mai-locations' ),
				__( 'Create a Map ID.', 'mai-locations' )
			);
		echo '</p>';
	}

	/**
	 * Fills in the Google Maps key and signature for ACF's map field, where ACF has none of its
	 * own. Until September 16, 2026 both conditions were always true, so a key saved here
	 * replaced whatever ACF already had.
	 *
	 * @since TBD
	 *
	 * @param array<string, mixed> $api The API data.
	 *
	 * @return array<string, mixed>
	 */
	public function acf_google_map_api( $api ) {
		// Maybe add key, only when ACF has none.
		if ( empty( $api['key'] ) ) {
			$key = mailocations_get_option( 'google_api_key' );

			if ( $key ) {
				$api['key'] = $key;
			}
		}

		// Maybe add signature, same rule.
		if ( empty( $api['signature'] ) ) {
			$signature = mailocations_get_option( 'google_api_signature' );

			if ( $signature ) {
				$api['signature'] = $signature;
			}
		}

		return $api;
	}

	/**
	 * Adds the Settings link to the plugin row. Only called while the plugin is active.
	 *
	 * @since TBD
	 *
	 * @param array<string, string> $actions     Action names to anchor tags.
	 * @param string                $plugin_file Plugin file name, such as my-plugin/my-plugin.php.
	 * @param array<string, mixed>  $plugin_data Plugin data from the plugin file headers.
	 * @param string                $context     Plugin status context: all, active, inactive, recently_active.
	 *
	 * @return array<string, string>
	 */
	public function add_settings_link( $actions, $plugin_file, $plugin_data, $context ) {
		$url    = esc_url( admin_url( 'edit.php?post_type=mai_location&page=mai-locations' ) );
		$custom = [
			'settings' => sprintf( '<a href="%s">%s</a>', $url, __( 'Settings', 'mai-locations' ) ),
		];

		return array_merge( $custom, $actions );
	}

	/**
	 * The "go and save permalinks" note shown under both base settings.
	 *
	 * @since TBD
	 *
	 * @return string
	 */
	private function permalink_instructions(): string {
		$link = sprintf( '<a href="%s">%s</a>', get_admin_url( null, 'options-permalink.php' ), __( 'Settings > Permalinks', 'mai-locations' ) );

		/* translators: %s: a link to Settings > Permalinks. */
		return sprintf( __( 'After changing this, go to %s and press Save.', 'mai-locations' ), $link );
	}
}
